[tasks.fmt]
run = "cargo fmt --all -- --check"

[tasks.clippy]
run = "cargo clippy --all-targets -- -D warnings"

[tasks.test]
run = "RUSTFLAGS=\"-D warnings\" cargo test --all-targets"

[tasks.pre-commit]
depends = ["fmt", "clippy", "test"]
